### ISSUE TITLE
TS Build error 

### ISSUE THREAD

**Issue by daysgobye** [qdrant/qdrant-js#48]
I have added this package to my nextjs project and I have this build error
![image](https://github.com/qdrant/qdrant-js/assets/38364556/449ee034-cbcc-40ff-8827-2d34be96cf0c)
if I update line 4 to this 
<img width="565" alt="image" src="https://github.com/qdrant/qdrant-js/assets/38364556/64eb3911-bb3e-46a2-a99e-84847e1a709c">
 everything builds no problem .
 
 So my questions: 
 Is this a true bug? 
 can I get my project to build another way? 
 Would this change be accepted as a pr, even thought I seem to be the only person running into this?
 
 here is my tsconfig

 {
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
      "es2022"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "types": [
      "cypress"
    ],
    "baseUrl": "./src",
    "paths": {
      "@lib/*": [
        "lib/*"
      ],
      "@modules/*": [
        "modules/*"
      ],
      "@pages/*": [
        "pages/*"
      ]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "cypress/support/index.js",
    "cypress/support/commands.js",
    "cypress/integration/product.spec.js",
    "cypress/plugins/index.js",
  ],
  "exclude": [
    "./node_modules/@qdrant",
    "node_modules",
    ".next",
    ".nyc_output",
    "cypress-coverage",
    "coverage",
    "jest-coverage"
  ]
}

and my package json 

{
  "name": "medusa-next",
  "version": "1.0.3",
  "private": true,
  "author": "Kasper Fabricius Kristensen <kasper@medusajs.com> (https://www.medusajs.com)",
  "description": "Next.js starter to be used with Medusa server",
  "keywords": [
    "medusa-storefront"
  ],
  "scripts": {
    "dev": "next dev -p 8000",
    "build": "next build",
    "start": "next start -p 8000",
    "lint": "next lint",
    "cypress": "cypress open",
    "analyze": "ANALYZE=true next build",
    "embedDocs": "tsx ./src/lib/util/ai/embeddDocs.ts"
  },
  "resolutions": {
    "webpack": "^5",
    "@types/react": "18.0.28"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.8",
    "@hookform/error-message": "^2.0.0",
    "@juggle/resize-observer": "^3.4.0",
    "@medusajs/medusa": "^1.10.0",
    "@medusajs/medusa-js": "^1.3.10",
    "@meilisearch/instant-meilisearch": "^0.7.1",
    "@paypal/paypal-js": "^5.0.6",
    "@paypal/react-paypal-js": "^7.8.1",
    "@pinecone-database/pinecone": "^1.0.0",
    "@popperjs/core": "^2.11.7",
    "@qdrant/js-client-rest": "^1.5.0",
    "@stripe/react-stripe-js": "^1.16.5",
    "@stripe/stripe-js": "^1.29.0",
    "@tanstack/react-query": "^4.29.5",
    "@vercel/analytics": "^1.0.2",
    "@xenova/transformers": "^2.6.0",
    "axios": "^1.1.3",
    "clsx": "^1.2.1",
    "daisyui": "^2.51.6",
    "langchain": "^0.0.146",
    "lodash": "^4.17.21",
    "medusa-react": "^7.0.0",
    "next": "^13.2.4",
    "next-mdx-remote": "^4.1.0",
    "nookies": "^2.5.2",
    "react": "^18.2.0",
    "react-confetti": "^6.1.0",
    "react-cool-dimensions": "^3.0.1",
    "react-country-flag": "^3.0.2",
    "react-country-region-selector": "^3.6.1",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.30.0",
    "react-hot-toast": "^2.4.0",
    "react-instantsearch-hooks-web": "^6.29.0",
    "react-intersection-observer": "^9.3.4",
    "react-popper": "^2.3.0",
    "remark-gfm": "^3.0.1",
    "sharp": "^0.30.7"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@tailwindcss/typography": "^0.5.9",
    "@types/node": "17.0.21",
    "@types/react": "17.0.40",
    "@types/react-instantsearch-dom": "^6.12.3",
    "autoprefixer": "^10.4.2",
    "babel-loader": "^8.2.3",
    "cypress": "^9.5.2",
    "eslint": "8.10.0",
    "eslint-config-next": "^13.2.4",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.4.8",
    "tailwindcss": "^3.0.23",
    "tsx": "^3.12.8",
    "typescript": "4.6.2"
  }
}

**Comment by kylevillegas93** [comment]
Ran into the same problem today trying to build after installing @qdrant/js-client-rest. 

Looks like other folks are experiencing the same [issue](https://stackoverflow.com/questions/77528955/qdrant-library-in-angular-project-compiling-problem)

**Comment by kylevillegas93** [comment]
I need top upgrade to a later version of typescript. I was on 4.5.4 and upgraded to 5.3.3. 

There were other dependencies that needed to bumped but that will be dependent on your package.json
