### ISSUE TITLE
how to encode str with nodejs?

### ISSUE THREAD

**Issue by wszgrcy** [qdrant/qdrant-js#75]
I checked the official examples: https://github.com/qdrant/qdrant-js/blob/master/examples/node-js-basic/index.js
But the document does not show how the vector value was obtained.
Can an interface be provided to load the 'all MiniLM-L6-v2' model? (Transformers has a JS version `@xenova/transformers` but still requires torch https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2)

**Comment by roysG** [comment]
Same issue

**Comment by roysG** [comment]
@wszgrcy, how dod you solved it?

**Comment by wszgrcy** [comment]
> @wszgrcy, how did you solved it?

use @xenova/transformers `pipeline`
